/*
 * easy-deploy
 * easy-deploy
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.27
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Token', 'model/UserInfo'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Token'), require('./UserInfo'));
  } else {
    // Browser globals (root is window)
    if (!root.EasyDeploy) {
      root.EasyDeploy = {};
    }
    root.EasyDeploy.AuthInfo = factory(root.EasyDeploy.ApiClient, root.EasyDeploy.Token, root.EasyDeploy.UserInfo);
  }
}(this, function(ApiClient, Token, UserInfo) {
  'use strict';

  /**
   * The AuthInfo model module.
   * @module model/AuthInfo
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>AuthInfo</code>.
   * @alias module:model/AuthInfo
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>AuthInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AuthInfo} obj Optional instance to populate.
   * @return {module:model/AuthInfo} The populated <code>AuthInfo</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('user_info'))
        obj.userInfo = UserInfo.constructFromObject(data['user_info']);
      if (data.hasOwnProperty('token'))
        obj.token = Token.constructFromObject(data['token']);
    }
    return obj;
  }

  /**
   * user's info
   * @member {module:model/UserInfo} userInfo
   */
  exports.prototype.userInfo = undefined;

  /**
   * token
   * @member {module:model/Token} token
   */
  exports.prototype.token = undefined;


  return exports;

}));
