/*
 * ez-deploy apiserver.
 * apiserver
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.27
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.EzDeployApiserver) {
      root.EzDeployApiserver = {};
    }
    root.EzDeployApiserver.EnvironmentVariable = factory(root.EzDeployApiserver.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The EnvironmentVariable model module.
   * @module model/EnvironmentVariable
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>EnvironmentVariable</code>.
   * Environment Variable for service deploy
   * @alias module:model/EnvironmentVariable
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>EnvironmentVariable</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/EnvironmentVariable} obj Optional instance to populate.
   * @return {module:model/EnvironmentVariable} The populated <code>EnvironmentVariable</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('service_id'))
        obj.serviceId = ApiClient.convertToType(data['service_id'], 'Number');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('value'))
        obj.value = ApiClient.convertToType(data['value'], 'String');
    }
    return obj;
  }

  /**
   * id
   * @member {Number} id
   */
  exports.prototype.id = undefined;

  /**
   * service id
   * @member {Number} serviceId
   */
  exports.prototype.serviceId = undefined;

  /**
   * environment variable name
   * @member {String} name
   */
  exports.prototype.name = undefined;

  /**
   * environment variable value
   * @member {String} value
   */
  exports.prototype.value = undefined;


  return exports;

}));
