/*
 * ez-deploy apiserver.
 * apiserver
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.27
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.EzDeployApiserver) {
      root.EzDeployApiserver = {};
    }
    root.EzDeployApiserver.GetTicketReq = factory(root.EzDeployApiserver.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The GetTicketReq model module.
   * @module model/GetTicketReq
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>GetTicketReq</code>.
   * SSH Pod Ticket Object
   * @alias module:model/GetTicketReq
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>GetTicketReq</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetTicketReq} obj Optional instance to populate.
   * @return {module:model/GetTicketReq} The populated <code>GetTicketReq</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('project_id'))
        obj.projectId = ApiClient.convertToType(data['project_id'], 'Number');
      if (data.hasOwnProperty('pod_name'))
        obj.podName = ApiClient.convertToType(data['pod_name'], 'String');
    }
    return obj;
  }

  /**
   * project id
   * @member {Number} projectId
   */
  exports.prototype.projectId = undefined;

  /**
   * pod name
   * @member {String} podName
   */
  exports.prototype.podName = undefined;


  return exports;

}));
