/*
 * ez-deploy apiserver.
 * apiserver
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.27
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.EzDeployApiserver) {
      root.EzDeployApiserver = {};
    }
    root.EzDeployApiserver.PodInfo = factory(root.EzDeployApiserver.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The PodInfo model module.
   * @module model/PodInfo
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>PodInfo</code>.
   * Pod Object
   * @alias module:model/PodInfo
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>PodInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PodInfo} obj Optional instance to populate.
   * @return {module:model/PodInfo} The populated <code>PodInfo</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], 'String');
      if (data.hasOwnProperty('restarts'))
        obj.restarts = ApiClient.convertToType(data['restarts'], 'Number');
      if (data.hasOwnProperty('age'))
        obj.age = ApiClient.convertToType(data['age'], 'String');
      if (data.hasOwnProperty('ip'))
        obj.ip = ApiClient.convertToType(data['ip'], 'String');
      if (data.hasOwnProperty('node'))
        obj.node = ApiClient.convertToType(data['node'], 'String');
    }
    return obj;
  }

  /**
   * unique name for pod
   * @member {String} name
   */
  exports.prototype.name = undefined;

  /**
   * pod status
   * @member {String} status
   */
  exports.prototype.status = undefined;

  /**
   * restart time
   * @member {Number} restarts
   */
  exports.prototype.restarts = undefined;

  /**
   * age of pod
   * @member {String} age
   */
  exports.prototype.age = undefined;

  /**
   * ip of pod
   * @member {String} ip
   */
  exports.prototype.ip = undefined;

  /**
   * node name
   * @member {String} node
   */
  exports.prototype.node = undefined;


  return exports;

}));
