/*
 * ez-deploy apiserver.
 * apiserver
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.27
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.EzDeployApiserver) {
      root.EzDeployApiserver = {};
    }
    root.EzDeployApiserver.ProjectInfo = factory(root.EzDeployApiserver.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The ProjectInfo model module.
   * @module model/ProjectInfo
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ProjectInfo</code>.
   * Project Object
   * @alias module:model/ProjectInfo
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>ProjectInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ProjectInfo} obj Optional instance to populate.
   * @return {module:model/ProjectInfo} The populated <code>ProjectInfo</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('owner_id'))
        obj.ownerId = ApiClient.convertToType(data['owner_id'], 'Number');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('create_at'))
        obj.createAt = ApiClient.convertToType(data['create_at'], 'Number');
      if (data.hasOwnProperty('update_at'))
        obj.updateAt = ApiClient.convertToType(data['update_at'], 'Number');
    }
    return obj;
  }

  /**
   * id
   * @member {Number} id
   */
  exports.prototype.id = undefined;

  /**
   * owner's user_id
   * @member {Number} ownerId
   */
  exports.prototype.ownerId = undefined;

  /**
   * project name
   * @member {String} name
   */
  exports.prototype.name = undefined;

  /**
   * project description
   * @member {String} description
   */
  exports.prototype.description = undefined;

  /**
   * create at, unix timestamp
   * @member {Number} createAt
   */
  exports.prototype.createAt = undefined;

  /**
   * update at, unix timestamp
   * @member {Number} updateAt
   */
  exports.prototype.updateAt = undefined;


  return exports;

}));
