/*
 * ez-deploy apiserver.
 * apiserver
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.27
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.EzDeployApiserver) {
      root.EzDeployApiserver = {};
    }
    root.EzDeployApiserver.RolePermission = factory(root.EzDeployApiserver.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The RolePermission model module.
   * @module model/RolePermission
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>RolePermission</code>.
   * Role Permissions Object
   * @alias module:model/RolePermission
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>RolePermission</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RolePermission} obj Optional instance to populate.
   * @return {module:model/RolePermission} The populated <code>RolePermission</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('role_id'))
        obj.roleId = ApiClient.convertToType(data['role_id'], 'Number');
      if (data.hasOwnProperty('permission'))
        obj.permission = ApiClient.convertToType(data['permission'], 'String');
    }
    return obj;
  }

  /**
   * id
   * @member {Number} id
   */
  exports.prototype.id = undefined;

  /**
   * AuthorityRole id
   * @member {Number} roleId
   */
  exports.prototype.roleId = undefined;

  /**
   * permission
   * @member {module:model/RolePermission.PermissionEnum} permission
   */
  exports.prototype.permission = undefined;



  /**
   * Allowed values for the <code>permission</code> property.
   * @enum {String}
   * @readonly
   */
  exports.PermissionEnum = {
    /**
     * value: "read"
     * @const
     */
    read: "read",

    /**
     * value: "write"
     * @const
     */
    write: "write",

    /**
     * value: "delete"
     * @const
     */
    _delete: "delete",

    /**
     * value: "deploy"
     * @const
     */
    deploy: "deploy"
  };

  return exports;

}));
