/*
 * ez-deploy apiserver.
 * apiserver
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.27
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.EzDeployApiserver) {
      root.EzDeployApiserver = {};
    }
    root.EzDeployApiserver.RoleInfo = factory(root.EzDeployApiserver.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The RoleInfo model module.
   * @module model/RoleInfo
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>RoleInfo</code>.
   * Authority Role Object
   * @alias module:model/RoleInfo
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>RoleInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RoleInfo} obj Optional instance to populate.
   * @return {module:model/RoleInfo} The populated <code>RoleInfo</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('project_id'))
        obj.projectId = ApiClient.convertToType(data['project_id'], 'Number');
      if (data.hasOwnProperty('role'))
        obj.role = ApiClient.convertToType(data['role'], 'String');
    }
    return obj;
  }

  /**
   * id
   * @member {Number} id
   */
  exports.prototype.id = undefined;

  /**
   * project id
   * @member {Number} projectId
   */
  exports.prototype.projectId = undefined;

  /**
   * role
   * @member {String} role
   */
  exports.prototype.role = undefined;


  return exports;

}));
