/*
 * ez-deploy apiserver.
 * apiserver
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.27
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.EzDeployApiserver) {
      root.EzDeployApiserver = {};
    }
    root.EzDeployApiserver.ServiceVersion = factory(root.EzDeployApiserver.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The ServiceVersion model module.
   * @module model/ServiceVersion
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ServiceVersion</code>.
   * Service Version Object
   * @alias module:model/ServiceVersion
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>ServiceVersion</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ServiceVersion} obj Optional instance to populate.
   * @return {module:model/ServiceVersion} The populated <code>ServiceVersion</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('service_id'))
        obj.serviceId = ApiClient.convertToType(data['service_id'], 'Number');
      if (data.hasOwnProperty('container_port'))
        obj.containerPort = ApiClient.convertToType(data['container_port'], 'Number');
      if (data.hasOwnProperty('image'))
        obj.image = ApiClient.convertToType(data['image'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('create_at'))
        obj.createAt = ApiClient.convertToType(data['create_at'], 'Number');
    }
    return obj;
  }

  /**
   * id
   * @member {Number} id
   */
  exports.prototype.id = undefined;

  /**
   * service id
   * @member {Number} serviceId
   */
  exports.prototype.serviceId = undefined;

  /**
   * container port
   * @member {Number} containerPort
   */
  exports.prototype.containerPort = undefined;

  /**
   * image name
   * @member {String} image
   */
  exports.prototype.image = undefined;

  /**
   * version name
   * @member {String} name
   */
  exports.prototype.name = undefined;

  /**
   * version description
   * @member {String} description
   */
  exports.prototype.description = undefined;

  /**
   * create at, unix timestamp
   * @member {Number} createAt
   */
  exports.prototype.createAt = undefined;


  return exports;

}));
