/*
 * ez-deploy apiserver.
 * apiserver
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.27
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.EzDeployApiserver) {
      root.EzDeployApiserver = {};
    }
    root.EzDeployApiserver.ServiceInfo = factory(root.EzDeployApiserver.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The ServiceInfo model module.
   * @module model/ServiceInfo
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ServiceInfo</code>.
   * Service Object
   * @alias module:model/ServiceInfo
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>ServiceInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ServiceInfo} obj Optional instance to populate.
   * @return {module:model/ServiceInfo} The populated <code>ServiceInfo</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('project_id'))
        obj.projectId = ApiClient.convertToType(data['project_id'], 'Number');
      if (data.hasOwnProperty('running'))
        obj.running = ApiClient.convertToType(data['running'], 'Boolean');
      if (data.hasOwnProperty('version_id'))
        obj.versionId = ApiClient.convertToType(data['version_id'], 'Number');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('replica'))
        obj.replica = ApiClient.convertToType(data['replica'], 'Number');
      if (data.hasOwnProperty('expose_type'))
        obj.exposeType = ApiClient.convertToType(data['expose_type'], 'String');
      if (data.hasOwnProperty('in_cluster_port'))
        obj.inClusterPort = ApiClient.convertToType(data['in_cluster_port'], 'Number');
      if (data.hasOwnProperty('node_port'))
        obj.nodePort = ApiClient.convertToType(data['node_port'], 'Number');
      if (data.hasOwnProperty('create_at'))
        obj.createAt = ApiClient.convertToType(data['create_at'], 'Number');
      if (data.hasOwnProperty('update_at'))
        obj.updateAt = ApiClient.convertToType(data['update_at'], 'Number');
    }
    return obj;
  }

  /**
   * id
   * @member {Number} id
   */
  exports.prototype.id = undefined;

  /**
   * project id
   * @member {Number} projectId
   */
  exports.prototype.projectId = undefined;

  /**
   * service is running or not
   * @member {Boolean} running
   */
  exports.prototype.running = undefined;

  /**
   * version id
   * @member {Number} versionId
   */
  exports.prototype.versionId = undefined;

  /**
   * service name
   * @member {String} name
   */
  exports.prototype.name = undefined;

  /**
   * service description
   * @member {String} description
   */
  exports.prototype.description = undefined;

  /**
   * number of pod replicas
   * @member {Number} replica
   */
  exports.prototype.replica = undefined;

  /**
   * expose service or not
   * @member {module:model/ServiceInfo.ExposeTypeEnum} exposeType
   */
  exports.prototype.exposeType = undefined;

  /**
   * in-cluster expose port
   * @member {Number} inClusterPort
   */
  exports.prototype.inClusterPort = undefined;

  /**
   * node-port expose port
   * @member {Number} nodePort
   */
  exports.prototype.nodePort = undefined;

  /**
   * create at, unix timestamp
   * @member {Number} createAt
   */
  exports.prototype.createAt = undefined;

  /**
   * update at, unix timestamp
   * @member {Number} updateAt
   */
  exports.prototype.updateAt = undefined;



  /**
   * Allowed values for the <code>exposeType</code> property.
   * @enum {String}
   * @readonly
   */
  exports.ExposeTypeEnum = {
    /**
     * value: "incluster"
     * @const
     */
    incluster: "incluster",

    /**
     * value: "nodeport"
     * @const
     */
    nodeport: "nodeport",

    /**
     * value: "none"
     * @const
     */
    none: "none"
  };

  return exports;

}));
