/*
 * ez-deploy apiserver.
 * apiserver
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.27
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.EzDeployApiserver) {
      root.EzDeployApiserver = {};
    }
    root.EzDeployApiserver.SSHPodTicket = factory(root.EzDeployApiserver.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The SSHPodTicket model module.
   * @module model/SSHPodTicket
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>SSHPodTicket</code>.
   * SSH Pod Ticket Object
   * @alias module:model/SSHPodTicket
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>SSHPodTicket</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SSHPodTicket} obj Optional instance to populate.
   * @return {module:model/SSHPodTicket} The populated <code>SSHPodTicket</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('ticket'))
        obj.ticket = ApiClient.convertToType(data['ticket'], 'String');
      if (data.hasOwnProperty('user_id'))
        obj.userId = ApiClient.convertToType(data['user_id'], 'Number');
      if (data.hasOwnProperty('namespace_name'))
        obj.namespaceName = ApiClient.convertToType(data['namespace_name'], 'String');
      if (data.hasOwnProperty('pod_name'))
        obj.podName = ApiClient.convertToType(data['pod_name'], 'String');
      if (data.hasOwnProperty('create_at'))
        obj.createAt = ApiClient.convertToType(data['create_at'], 'Number');
    }
    return obj;
  }

  /**
   * id
   * @member {Number} id
   */
  exports.prototype.id = undefined;

  /**
   * ticket
   * @member {String} ticket
   */
  exports.prototype.ticket = undefined;

  /**
   * user id
   * @member {Number} userId
   */
  exports.prototype.userId = undefined;

  /**
   * namespace name
   * @member {String} namespaceName
   */
  exports.prototype.namespaceName = undefined;

  /**
   * pod name
   * @member {String} podName
   */
  exports.prototype.podName = undefined;

  /**
   * create at, unix timestamp
   * @member {Number} createAt
   */
  exports.prototype.createAt = undefined;


  return exports;

}));
