/*
 * ez-deploy apiserver.
 * apiserver
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.27
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./RoleView'));
  } else {
    // Browser globals (root is window)
    if (!root.EzDeployApiserver) {
      root.EzDeployApiserver = {};
    }
    root.EzDeployApiserver.UserRole = factory(root.EzDeployApiserver.ApiClient, root.EzDeployApiserver.RoleView);
  }
}(this, function(ApiClient, RoleView) {
  'use strict';

  /**
   * The UserRole model module.
   * @module model/UserRole
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>UserRole</code>.
   * User Role Object
   * @alias module:model/UserRole
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>UserRole</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UserRole} obj Optional instance to populate.
   * @return {module:model/UserRole} The populated <code>UserRole</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('user_id'))
        obj.userId = ApiClient.convertToType(data['user_id'], 'Number');
      if (data.hasOwnProperty('roles'))
        obj.roles = ApiClient.convertToType(data['roles'], [RoleView]);
    }
    return obj;
  }

  /**
   * user_id
   * @member {Number} userId
   */
  exports.prototype.userId = undefined;

  /**
   * roles
   * @member {Array.<module:model/RoleView>} roles
   */
  exports.prototype.roles = undefined;


  return exports;

}));
