/*
 * ez-deploy apiserver.
 * apiserver
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.27
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/Error'), require('../model/ProjectRole'), require('../model/UserRole'));
  } else {
    // Browser globals (root is window)
    if (!root.EzDeployApiserver) {
      root.EzDeployApiserver = {};
    }
    root.EzDeployApiserver.RBACApi = factory(root.EzDeployApiserver.ApiClient, root.EzDeployApiserver.Error, root.EzDeployApiserver.ProjectRole, root.EzDeployApiserver.UserRole);
  }
}(this, function(ApiClient, Error, ProjectRole, UserRole) {
  'use strict';

  /**
   * RBAC service.
   * @module api/RBACApi
   * @version 1.0.0
   */

  /**
   * Constructs a new RBACApi. 
   * @alias module:api/RBACApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the getProjectRBAC operation.
     * @callback module:api/RBACApi~getProjectRBACCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ProjectRole} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Project RBAC
     * @param {Number} id projectID
     * @param {module:api/RBACApi~getProjectRBACCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ProjectRole}
     */
    this.getProjectRBAC = function(id, callback) {
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getProjectRBAC");
      }


      var pathParams = {
      };
      var queryParams = {
        'id': id,
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['key'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = ProjectRole;

      return this.apiClient.callApi(
        '/rbac/project/get', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getUserRBAC operation.
     * @callback module:api/RBACApi~getUserRBACCallback
     * @param {String} error Error message, if any.
     * @param {module:model/UserRole} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get User RBAC
     * @param {module:api/RBACApi~getUserRBACCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/UserRole}
     */
    this.getUserRBAC = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['key'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = UserRole;

      return this.apiClient.callApi(
        '/rbac/user/get', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
