/*
 * ez-deploy apiserver.
 * apiserver
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.27
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EzDeployApiserver);
  }
}(this, function(expect, EzDeployApiserver) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('AuthInfo', function() {
      beforeEach(function() {
        instance = new EzDeployApiserver.AuthInfo();
      });

      it('should create an instance of AuthInfo', function() {
        // TODO: update the code to test AuthInfo
        expect(instance).to.be.a(EzDeployApiserver.AuthInfo);
      });

      it('should have the property userInfo (base name: "user_info")', function() {
        // TODO: update the code to test the property userInfo
        expect(instance).to.have.property('userInfo');
        // expect(instance.userInfo).to.be(expectedValueLiteral);
      });

      it('should have the property token (base name: "token")', function() {
        // TODO: update the code to test the property token
        expect(instance).to.have.property('token');
        // expect(instance.token).to.be(expectedValueLiteral);
      });

    });
  });

}));
