/*
 * ez-deploy apiserver.
 * apiserver
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.27
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EzDeployApiserver);
  }
}(this, function(expect, EzDeployApiserver) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('GetTicketReq', function() {
      beforeEach(function() {
        instance = new EzDeployApiserver.GetTicketReq();
      });

      it('should create an instance of GetTicketReq', function() {
        // TODO: update the code to test GetTicketReq
        expect(instance).to.be.a(EzDeployApiserver.GetTicketReq);
      });

      it('should have the property projectId (base name: "project_id")', function() {
        // TODO: update the code to test the property projectId
        expect(instance).to.have.property('projectId');
        // expect(instance.projectId).to.be(expectedValueLiteral);
      });

      it('should have the property podName (base name: "pod_name")', function() {
        // TODO: update the code to test the property podName
        expect(instance).to.have.property('podName');
        // expect(instance.podName).to.be(expectedValueLiteral);
      });

    });
  });

}));
