/*
 * ez-deploy apiserver.
 * apiserver
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.27
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EzDeployApiserver);
  }
}(this, function(expect, EzDeployApiserver) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('ProjectInfo', function() {
      beforeEach(function() {
        instance = new EzDeployApiserver.ProjectInfo();
      });

      it('should create an instance of ProjectInfo', function() {
        // TODO: update the code to test ProjectInfo
        expect(instance).to.be.a(EzDeployApiserver.ProjectInfo);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property ownerId (base name: "owner_id")', function() {
        // TODO: update the code to test the property ownerId
        expect(instance).to.have.property('ownerId');
        // expect(instance.ownerId).to.be(expectedValueLiteral);
      });

      it('should have the property name (base name: "name")', function() {
        // TODO: update the code to test the property name
        expect(instance).to.have.property('name');
        // expect(instance.name).to.be(expectedValueLiteral);
      });

      it('should have the property description (base name: "description")', function() {
        // TODO: update the code to test the property description
        expect(instance).to.have.property('description');
        // expect(instance.description).to.be(expectedValueLiteral);
      });

      it('should have the property createAt (base name: "create_at")', function() {
        // TODO: update the code to test the property createAt
        expect(instance).to.have.property('createAt');
        // expect(instance.createAt).to.be(expectedValueLiteral);
      });

      it('should have the property updateAt (base name: "update_at")', function() {
        // TODO: update the code to test the property updateAt
        expect(instance).to.have.property('updateAt');
        // expect(instance.updateAt).to.be(expectedValueLiteral);
      });

    });
  });

}));
