/*
 * ez-deploy apiserver.
 * apiserver
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.27
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EzDeployApiserver);
  }
}(this, function(expect, EzDeployApiserver) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('RolePermission', function() {
      beforeEach(function() {
        instance = new EzDeployApiserver.RolePermission();
      });

      it('should create an instance of RolePermission', function() {
        // TODO: update the code to test RolePermission
        expect(instance).to.be.a(EzDeployApiserver.RolePermission);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property roleId (base name: "role_id")', function() {
        // TODO: update the code to test the property roleId
        expect(instance).to.have.property('roleId');
        // expect(instance.roleId).to.be(expectedValueLiteral);
      });

      it('should have the property permission (base name: "permission")', function() {
        // TODO: update the code to test the property permission
        expect(instance).to.have.property('permission');
        // expect(instance.permission).to.be(expectedValueLiteral);
      });

    });
  });

}));
