/*
 * ez-deploy apiserver.
 * apiserver
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.27
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EzDeployApiserver);
  }
}(this, function(expect, EzDeployApiserver) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('ServiceInfo', function() {
      beforeEach(function() {
        instance = new EzDeployApiserver.ServiceInfo();
      });

      it('should create an instance of ServiceInfo', function() {
        // TODO: update the code to test ServiceInfo
        expect(instance).to.be.a(EzDeployApiserver.ServiceInfo);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property projectId (base name: "project_id")', function() {
        // TODO: update the code to test the property projectId
        expect(instance).to.have.property('projectId');
        // expect(instance.projectId).to.be(expectedValueLiteral);
      });

      it('should have the property running (base name: "running")', function() {
        // TODO: update the code to test the property running
        expect(instance).to.have.property('running');
        // expect(instance.running).to.be(expectedValueLiteral);
      });

      it('should have the property versionId (base name: "version_id")', function() {
        // TODO: update the code to test the property versionId
        expect(instance).to.have.property('versionId');
        // expect(instance.versionId).to.be(expectedValueLiteral);
      });

      it('should have the property name (base name: "name")', function() {
        // TODO: update the code to test the property name
        expect(instance).to.have.property('name');
        // expect(instance.name).to.be(expectedValueLiteral);
      });

      it('should have the property description (base name: "description")', function() {
        // TODO: update the code to test the property description
        expect(instance).to.have.property('description');
        // expect(instance.description).to.be(expectedValueLiteral);
      });

      it('should have the property replica (base name: "replica")', function() {
        // TODO: update the code to test the property replica
        expect(instance).to.have.property('replica');
        // expect(instance.replica).to.be(expectedValueLiteral);
      });

      it('should have the property exposeType (base name: "expose_type")', function() {
        // TODO: update the code to test the property exposeType
        expect(instance).to.have.property('exposeType');
        // expect(instance.exposeType).to.be(expectedValueLiteral);
      });

      it('should have the property inClusterPort (base name: "in_cluster_port")', function() {
        // TODO: update the code to test the property inClusterPort
        expect(instance).to.have.property('inClusterPort');
        // expect(instance.inClusterPort).to.be(expectedValueLiteral);
      });

      it('should have the property nodePort (base name: "node_port")', function() {
        // TODO: update the code to test the property nodePort
        expect(instance).to.have.property('nodePort');
        // expect(instance.nodePort).to.be(expectedValueLiteral);
      });

      it('should have the property createAt (base name: "create_at")', function() {
        // TODO: update the code to test the property createAt
        expect(instance).to.have.property('createAt');
        // expect(instance.createAt).to.be(expectedValueLiteral);
      });

      it('should have the property updateAt (base name: "update_at")', function() {
        // TODO: update the code to test the property updateAt
        expect(instance).to.have.property('updateAt');
        // expect(instance.updateAt).to.be(expectedValueLiteral);
      });

    });
  });

}));
