/*
 * ez-deploy apiserver.
 * apiserver
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.27
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EzDeployApiserver);
  }
}(this, function(expect, EzDeployApiserver) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('SSHPodTicket', function() {
      beforeEach(function() {
        instance = new EzDeployApiserver.SSHPodTicket();
      });

      it('should create an instance of SSHPodTicket', function() {
        // TODO: update the code to test SSHPodTicket
        expect(instance).to.be.a(EzDeployApiserver.SSHPodTicket);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property ticket (base name: "ticket")', function() {
        // TODO: update the code to test the property ticket
        expect(instance).to.have.property('ticket');
        // expect(instance.ticket).to.be(expectedValueLiteral);
      });

      it('should have the property userId (base name: "user_id")', function() {
        // TODO: update the code to test the property userId
        expect(instance).to.have.property('userId');
        // expect(instance.userId).to.be(expectedValueLiteral);
      });

      it('should have the property namespaceName (base name: "namespace_name")', function() {
        // TODO: update the code to test the property namespaceName
        expect(instance).to.have.property('namespaceName');
        // expect(instance.namespaceName).to.be(expectedValueLiteral);
      });

      it('should have the property podName (base name: "pod_name")', function() {
        // TODO: update the code to test the property podName
        expect(instance).to.have.property('podName');
        // expect(instance.podName).to.be(expectedValueLiteral);
      });

      it('should have the property createAt (base name: "create_at")', function() {
        // TODO: update the code to test the property createAt
        expect(instance).to.have.property('createAt');
        // expect(instance.createAt).to.be(expectedValueLiteral);
      });

    });
  });

}));
