/*
 * easy-deploy
 * easy-deploy
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.27
 *
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/AuthInfo'), require('./model/Error'), require('./model/Token'), require('./model/UserInfo'), require('./api/IdentityApi'));
  }
}(function(ApiClient, AuthInfo, Error, Token, UserInfo, IdentityApi) {
  'use strict';

  /**
   * easy_deploy.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var EasyDeploy = require('index'); // See note below*.
   * var xxxSvc = new EasyDeploy.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new EasyDeploy.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new EasyDeploy.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new EasyDeploy.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 1.0.0
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The AuthInfo model constructor.
     * @property {module:model/AuthInfo}
     */
    AuthInfo: AuthInfo,
    /**
     * The Error model constructor.
     * @property {module:model/Error}
     */
    Error: Error,
    /**
     * The Token model constructor.
     * @property {module:model/Token}
     */
    Token: Token,
    /**
     * The UserInfo model constructor.
     * @property {module:model/UserInfo}
     */
    UserInfo: UserInfo,
    /**
     * The IdentityApi service constructor.
     * @property {module:api/IdentityApi}
     */
    IdentityApi: IdentityApi
  };

  return exports;
}));
