/*
 * ez-deploy apiserver.
 * apiserver
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.27
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EzDeployApiserver);
  }
}(this, function(expect, EzDeployApiserver) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new EzDeployApiserver.ProjectApi();
  });

  describe('(package)', function() {
    describe('ProjectApi', function() {
      describe('createProject', function() {
        it('should call createProject successfully', function(done) {
          // TODO: uncomment, update parameter values for createProject call and complete the assertions
          /*
          var body = new EzDeployApiserver.ProjectInfo();
          body.id = 1;
          body.ownerId = 1;
          body.name = "foobar";
          body.description = "foobar project";
          body.createAt = 1528894200;
          body.updateAt = 1528894200;

          instance.createProject(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(EzDeployApiserver.ProjectInfo);
            expect(data.id).to.be.a('number');
            expect(data.id).to.be(1);
            expect(data.ownerId).to.be.a('number');
            expect(data.ownerId).to.be(1);
            expect(data.name).to.be.a('string');
            expect(data.name).to.be("foobar");
            expect(data.description).to.be.a('string');
            expect(data.description).to.be("foobar project");
            expect(data.createAt).to.be.a('number');
            expect(data.createAt).to.be(1528894200);
            expect(data.updateAt).to.be.a('number');
            expect(data.updateAt).to.be(1528894200);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getProject', function() {
        it('should call getProject successfully', function(done) {
          // TODO: uncomment, update parameter values for getProject call and complete the assertions
          /*
          var id = 56;

          instance.getProject(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(EzDeployApiserver.ProjectInfo);
            expect(data.id).to.be.a('number');
            expect(data.id).to.be(1);
            expect(data.ownerId).to.be.a('number');
            expect(data.ownerId).to.be(1);
            expect(data.name).to.be.a('string');
            expect(data.name).to.be("foobar");
            expect(data.description).to.be.a('string');
            expect(data.description).to.be("foobar project");
            expect(data.createAt).to.be.a('number');
            expect(data.createAt).to.be(1528894200);
            expect(data.updateAt).to.be.a('number');
            expect(data.updateAt).to.be(1528894200);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
